import React, { useState, useEffect, useRef, useContext } from 'react';
import axios from 'axios';
import { FaComments, FaUserMd, FaDownload } from 'react-icons/fa';
import jsPDF from 'jspdf';
import { toast } from 'react-toastify';
import { AppContext } from '../context/AppContext';

const DrAIChat = () => {
  const { userData, token } = useContext(AppContext);
  const backendUrl = import.meta.env.VITE_BACKEND_URL;

  const [isOpen, setIsOpen] = useState(false);
  const [step, setStep] = useState(0);
  const [answers, setAnswers] = useState({
    symptoms: '',
    duration: '',
    history: '',
    medications: '',
    allergies: '',
  });
  const [messages, setMessages] = useState([
    { from: 'ai', text: "Hello! I'm Dr.AI. Let's create your health report." },
    { from: 'ai', text: "What symptoms are you experiencing?" }
  ]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [isReportReady, setIsReportReady] = useState(false);
  const bottomRef = useRef(null);

  const questions = [
    { key: 'symptoms', question: "What symptoms are you experiencing?" },
    { key: 'duration', question: "For how long have you had these symptoms?" },
    { key: 'history', question: "Do you have any relevant medical history?" },
    { key: 'medications', question: "Are you currently taking any medications?" },
    { key: 'allergies', question: "Do you have any allergies?" }
  ];

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  // handle next question or generate report
  const handleNext = async () => {
    if (!input.trim() || isLoading || step === -1) return;

    const currentStep = questions[step];
    const updatedAnswers = { ...answers, [currentStep.key]: input };

    const newMessages = [
      ...messages,
      { from: 'user', text: input }
    ];

    setAnswers(updatedAnswers);
    setInput('');

    if (step < questions.length - 1) {
      // Ask next question
      setStep(step + 1);
      setMessages([
        ...newMessages,
        { from: 'ai', text: questions[step + 1].question }
      ]);
    } else {
      // All questions answered – call AI to generate report
      setIsLoading(true);
      setMessages([
        ...newMessages,
        { from: 'ai', text: "Generating your prescription..." }
      ]);

      try {
        const patientName = userData?.name || '[Patient Name]';
        const date = new Date().toLocaleDateString();

        const summary = `
Patient Name: ${patientName}
Date: ${date}

Symptoms: ${updatedAnswers.symptoms}
Duration: ${updatedAnswers.duration}
Medical History: ${updatedAnswers.history}
Medications: ${updatedAnswers.medications}
Allergies: ${updatedAnswers.allergies}
`;

        const promptText = `
You are an experienced licensed doctor. Based on the following patient information, generate a clean, professional PRESCRIPTION REPORT in plain text (not raw markdown).

Include these sections:
- Clinical Summary (brief analysis and what might be happening)
- Diagnosis (one line)
- Recommended Tests (list of tests with brief purpose)
- Treatment Plan (detailed plan with dosages, frequency, duration)
- List of Medication Prescribed (with name, dosage, frequency, quantity, refills)
- Special Instructions & Advice (numbered or bulleted)
- Prescriber info (write as Dr.AI, AI Assistant)

At the end, add:
"Generated by AI for preliminary guidance only – please consult a qualified doctor for confirmation."

**Patient Information:**  
${summary}
`;

        const response = await axios.post(
          `${backendUrl}/api/ai/ask`,
          { messages: [{ from: 'user', text: promptText }] },
          { headers: { token } }
        );

        setMessages([
          ...newMessages,
          { from: 'ai', text: "Generating your prescription..." },
          { from: 'ai', text: response?.data?.text || response?.data?.answer || "Here’s your prescription." },
          { from: 'ai', text: "Your report is ready! If you wish to generate another report, please click below to restart." }
        ]);
        setIsReportReady(true);
        setStep(-1); // disable further input
      } catch (err) {
        console.error(err);
        toast.error('Failed to generate prescription');
        setMessages([
          ...newMessages,
          { from: 'ai', text: "Sorry, something went wrong while generating your report." }
        ]);
      } finally {
        setIsLoading(false);
      }
    }
  };

  // Generate clean PDF from AI message
  const handleDownload = () => {
    const prescriptionMsg = messages.find(
      msg => msg.from === 'ai' && msg.text.includes('PRESCRIPTION REPORT')
    );

    if (!prescriptionMsg) {
      toast.error('No report available to download.');
      return;
    }

    const doc = new jsPDF();
    let y = 10;

    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('PRESCRIPTION REPORT', 10, y);
    y += 10;

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');

    const lines = doc.splitTextToSize(prescriptionMsg.text, 180);
    lines.forEach(line => {
      doc.text(line, 10, y);
      y += 8;
      if (y > 280) {
        doc.addPage();
        y = 10;
      }
    });

    y += 5;
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text('Generated by AI – please consult a qualified doctor.', 10, y);

    doc.save(`DrAI_Report_${new Date().toISOString().slice(0,10)}.pdf`);
  };

  const handleRestart = () => {
    setStep(0);
    setAnswers({
      symptoms: '',
      duration: '',
      history: '',
      medications: '',
      allergies: '',
    });
    setInput('');
    setMessages([
      { from: 'ai', text: "Hello again! Let's create a new health report." },
      { from: 'ai', text: questions[0].question }
    ]);
    setIsReportReady(false);
  };

  return (
    <div>
      {/* Floating Chat Button */}
      {!isOpen && (
        <div className="fixed bottom-5 right-5 flex flex-col items-center space-y-1 z-50">
          <div className="bg-teal-600 text-white text-xs px-2 py-0.5 rounded-full shadow-md">
            Dr.AI
          </div>
          <button
            onClick={() => {
              if (!userData) {
                toast.error("Please login first to use Dr.AI");
                return;
              }
              setIsOpen(true);
            }}
            className="bg-teal-600 text-white p-4 rounded-full shadow-lg hover:bg-teal-700"
            aria-label="Open Dr.AI Chat"
          >
            <FaComments size={24} />
          </button>
        </div>
      )}

      {/* Chat Box */}
      {isOpen && (
        <div className="fixed bottom-0 right-0 md:right-10 mb-5 w-full max-w-md md:max-w-lg h-[75%] bg-white border border-gray-300 rounded-xl shadow-2xl flex flex-col z-50">
          {/* Header */}
          <div className="flex items-center p-4 bg-teal-600 text-white rounded-t-xl">
            <FaUserMd className="mr-3 text-xl" />
            <div>
              <div className="font-semibold text-lg">Dr.AI</div>
              <div className="text-xs">Free AI-powered medical assistant</div>
            </div>
            <button
              onClick={() => setIsOpen(false)}
              className="ml-auto text-xl font-bold hover:text-gray-300"
              aria-label="Close chat"
            >
              &times;
            </button>
          </div>

          {/* Messages */}
          <div className="flex-1 p-4 overflow-y-auto bg-gray-50 space-y-3">
            {messages.map((msg, idx) => (
              <div
                key={idx}
                className={`p-3 rounded-xl text-sm whitespace-pre-wrap max-w-[80%] ${
                  msg.from === 'user'
                    ? 'bg-teal-100 self-end'
                    : 'bg-white border border-gray-200 self-start'
                }`}
              >
                {msg.text}
              </div>
            ))}
            {isLoading && (
              <div className="p-3 rounded-xl text-sm bg-white border border-gray-200 self-start">
                Typing...
              </div>
            )}

            {/* Download + Restart */}
            {isReportReady && (
              <div className="self-center text-center mt-4 space-y-3">
                <button
                  onClick={handleDownload}
                  className="flex items-center gap-2 px-4 py-2 bg-teal-600 text-white rounded-full text-sm hover:bg-teal-700"
                >
                  <FaDownload />
                  Download Report (PDF)
                </button>
                <button
                  onClick={handleRestart}
                  className="text-teal-600 hover:underline text-sm"
                >
                  Start New Report
                </button>
              </div>
            )}
            <div ref={bottomRef} />
          </div>

          {/* Input */}
          <div className="p-3 border-t border-gray-200 bg-white rounded-b-xl flex space-x-2">
            {!isLoading && step !== -1 && (
              <>
                <input
                  type="text"
                  className="flex-1 border border-gray-300 rounded-full px-4 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-teal-500"
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && handleNext()}
                  placeholder="Type your answer..."
                  aria-label="User input"
                />
                <button
                  onClick={handleNext}
                  className="bg-teal-600 text-white px-4 py-2 rounded-full text-sm hover:bg-teal-700"
                  aria-label="Send message"
                >
                  Send
                </button>
              </>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

export default DrAIChat;
